name: curs
channels:
  - conda-forge
dependencies:
  - python~=3.10.0
  - pip
  - numpy
  - scipy
  - matplotlib
  - ipympl
  - sphinx
  - sphinx-copybutton
  - notebook<7
  - rise
  - pip:
    - flake8_nb
    - black[jupyter]

