name: diffeq
channels:
  - conda-forge
dependencies:
  - python~=3.10.0
  - pip
  - numpy
  - scipy
  - matplotlib
  - ipympl
  - notebook<7 # Version larger than 7 does not work with RISE.
  - rise # For using notebooks as slides.
  - sphinx # For building documentation.
  - sphinx-copybutton
  - sphinx-rtd-theme # Theme used for documentation. More themes: https://sphinx-themes.org.
  - nbsphinx
  - nbsphinx-link
  - pip:
      - flake8_nb
      - black[jupyter]
      - myst_parser
