name: diffeq
channels:
  - conda-forge
dependencies:
  - python~=3.10.0
  - pip
  - numpy
  - scipy
  - matplotlib
  - ipympl
  - sphinx
  - sphinx-copybutton
  - notebook<7
  - rise
  - nbsphinx
  - nbsphinx-link
  - sphinx-copybutton
  - sphinx-rtd-theme
  - pip:
      - flake8_nb
      - black[jupyter]
